### ISSUE TITLE
Wikifundi package extraction issue

### ISSUE THREAD

**Issue by rgaudin** [offspot/offspot-config#17]
```
[2023-12-23 22:00:24]    => Downloading 9 files totaling 10.92 GiB… using 9 workers
[Elapsed Time: 0:00:00]   0.0 B of 10.92 GiB downloaded||  0.0 s/B (ETA:  --:--:--)
ERROR: exception calling callback for <Future at 0x7f2489247910 state=finished raised IsADirectoryError>
Traceback (most recent call last):
  File "/tmp/onefile_8_1703368552_523722/concurrent/futures/_base.py", line 340, in _invoke_callbacks
  File "/tmp/onefile_8_1703368552_523722/image_creator/steps/contents.py", line 200, in notify_completion
  File "/tmp/onefile_8_1703368552_523722/concurrent/futures/_base.py", line 449, in result
  File "/tmp/onefile_8_1703368552_523722/concurrent/futures/_base.py", line 401, in __get_result
  File "/tmp/onefile_8_1703368552_523722/concurrent/futures/thread.py", line 58, in run
  File "/tmp/onefile_8_1703368552_523722/image_creator/steps/contents.py", line 117, in download_file_worker
  File "/tmp/onefile_8_1703368552_523722/image_creator/utils/download.py", line 50, in download_file
IsADirectoryError: [Errno 21] Is a directory: '/tmp/part3_avhbah3l/contents/wikifundi-fr.offspot.kiwix.org'
[Elapsed Time: 0:00:00]   0.0 B of 10.92 GiB downloaded||  0.0 s/B (ETA:  --:--:--)
[Elapsed Time: 0:00:00]   0.0 B of 10.92 GiB downloaded||  0.0 s/B (ETA:  --:--:--)
```

**Comment by rgaudin** [comment]
Fixed in 0cbf415
